apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/launch-stage: BETA
  name: ${SERVICE_NAME}
spec:
  template:
    metadata:
      labels:
        revision: "1"
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/container-dependencies: '{"app":["envoy"]}'
    spec:
      containers:
        - name: envoy
          image: asia-northeast1-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY_NAME}/envoy:latest
          resources:
            limits:
              memory: 256Mi
          ports:
            - containerPort: 9001
          env:
            - name: PROXY_TARGET_ADDRESS
              value: 127.0.0.1
        - name: app
          image: asia-northeast1-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY_NAME}/app:latest
          resources:
            limits:
              memory: 256Mi
